FROM lukemathwalker/cargo-chef:latest-rust-1 AS chef
RUN apt-get update && apt-get install -y musl-tools musl-dev
RUN update-ca-certificates
WORKDIR /app


ARG DISPLEX_HOSTNAME
ARG DISPLEX_APPLICATION_NAME
ARG DISPLEX_PLEX_SERVER_ID
ARG DISPLEX_DISCORD_CLIENT_ID
ARG DISPLEX_DISCORD_CLIENT_SECRET
ARG DISPLEX_DISCORD_BOT_TOKEN
ARG DISPLEX_DISCORD_SERVER_ID
ARG DISPLEX_DISCORD_CHANNEL_ID
ARG DISPLEX_SESSION_SECRET_KEY
ARG DISPLEX_TAUTULLI_API_KEY
ARG DISPLEX_TAUTULLI_URL
ARG DISPLEX_ACCEPT_INVALID_CERTS
ARG DISPLEX_DATABASE_URL
ARG DATABASE_URL
ARG RUST_LOG
ARG DISPLEX_DISCORD_BOT_STAT_CATEGORY_NAME
ARG DISPLEX_DISCORD_BOT_STAT_STATUS_NAME
ARG DISPLEX_DISCORD_BOT_STAT_STREAM_NAME
ARG DISPLEX_DISCORD_BOT_STAT_TRANSCODE_NAME
ARG DISPLEX_DISCORD_BOT_STAT_BANDWIDTH_NAME
ARG DISPLEX_DISCORD_BOT_LIB_CATEGORY_NAME
ARG DISPLEX_DISCORD_BOT_LIB_MOVIES_NAME
ARG DISPLEX_DISCORD_BOT_LIB_TV_SHOWS_NAME
ARG DISPLEX_DISCORD_BOT_LIB_TV_EPISODES_NAME

ENV DISPLEX_HOSTNAME=$DISPLEX_HOSTNAME
ENV DISPLEX_APPLICATION_NAME=$DISPLEX_APPLICATION_NAME
ENV DISPLEX_PLEX_SERVER_ID=$DISPLEX_PLEX_SERVER_ID
ENV DISPLEX_DISCORD_CLIENT_ID=$DISPLEX_DISCORD_CLIENT_ID
ENV DISPLEX_DISCORD_CLIENT_SECRET=$DISPLEX_DISCORD_CLIENT_SECRET
ENV DISPLEX_DISCORD_BOT_TOKEN=$DISPLEX_DISCORD_BOT_TOKEN
ENV DISPLEX_DISCORD_SERVER_ID=$DISPLEX_DISCORD_SERVER_ID
ENV DISPLEX_DISCORD_CHANNEL_ID=$DISPLEX_DISCORD_CHANNEL_ID
ENV DISPLEX_SESSION_SECRET_KEY=$DISPLEX_SESSION_SECRET_KEY
ENV DISPLEX_TAUTULLI_API_KEY=$DISPLEX_TAUTULLI_API_KEY
ENV DISPLEX_TAUTULLI_URL=$DISPLEX_TAUTULLI_URL
ENV DISPLEX_ACCEPT_INVALID_CERTS=$DISPLEX_ACCEPT_INVALID_CERTS
ENV DISPLEX_DATABASE_URL=$DISPLEX_DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
ENV RUST_LOG=$RUST_LOG
ENV DISPLEX_DISCORD_BOT_STAT_CATEGORY_NAME=$DISPLEX_DISCORD_BOT_STAT_CATEGORY_NAME
ENV DISPLEX_DISCORD_BOT_STAT_STATUS_NAME=$DISPLEX_DISCORD_BOT_STAT_STATUS_NAME
ENV DISPLEX_DISCORD_BOT_STAT_STREAM_NAME=$DISPLEX_DISCORD_BOT_STAT_STREAM_NAME
ENV DISPLEX_DISCORD_BOT_STAT_TRANSCODE_NAME=$DISPLEX_DISCORD_BOT_STAT_TRANSCODE_NAME
ENV DISPLEX_DISCORD_BOT_STAT_BANDWIDTH_NAME=$DISPLEX_DISCORD_BOT_STAT_BANDWIDTH_NAME
ENV DISPLEX_DISCORD_BOT_LIB_CATEGORY_NAME=$DISPLEX_DISCORD_BOT_LIB_CATEGORY_NAME
ENV DISPLEX_DISCORD_BOT_LIB_MOVIES_NAME=$DISPLEX_DISCORD_BOT_LIB_MOVIES_NAME
ENV DISPLEX_DISCORD_BOT_LIB_TV_SHOWS_NAME=$DISPLEX_DISCORD_BOT_LIB_TV_SHOWS_NAME
ENV DISPLEX_DISCORD_BOT_LIB_TV_EPISODES_NAME=$DISPLEX_DISCORD_BOT_LIB_TV_EPISODES_NAME


FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS app-builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --profile dist --recipe-path recipe.json
COPY . .
RUN rustup target add x86_64-unknown-linux-musl
RUN cargo build --profile dist --bin displex --target x86_64-unknown-linux-musl

# taken from https://medium.com/@lizrice/non-privileged-containers-based-on-the-scratch-image-a80105d6d341
FROM ubuntu:latest as user-creator
RUN groupadd -g 1001 displex \
        && useradd -u 1001 -g 1001 displex \
        && mkdir /data \
        && chown -R displex:displex /data
        
FROM scratch AS runtime
COPY --from=user-creator /etc/passwd /etc/passwd
COPY --from=user-creator /etc/group /etc/group
COPY --from=user-creator --chown=displex:displex /data /data
#COPY --from=user-creator --chown=displex:displex .env /app/.env

VOLUME [ "/data" ]
WORKDIR /data

USER displex
ENV RUST_LOG="displex=debug,sea_orm=debug" \
    DISPLEX_HTTP__HOST=0.0.0.0 \
    DISPLEX_HTTP__PORT=8080 \
    DATABASE_URL=sqlite://displex.db?mode=rwc
COPY --from=app-builder --chown=displex:displex /app/target/x86_64-unknown-linux-musl/dist/displex /app

ENTRYPOINT ["/app"]


